export const appDataConfigTypes = {
  APP_DATA_CONFIG_UPDATE: 'APP_DATA_CONFIG_UPDATE',
};

export const postDataTypes = {
  POST_DATA_UPDATE: 'POST_DATA_UPDATE',
  POST_DATA_DISABLE_UNREAD: 'POST_DATA_DISABLE_UNREAD',
  POST_DATA_ADD_FAVORITE: 'POST_DATA_ADD_FAVORITE',
  POST_DATA_HIDE_FAVORITE: 'POST_DATA_HIDE_FAVORITE',
  POST_DATA_DELETE_ITEM: 'POST_DATA_DELETE_ITEM',
  POST_DATA_TRY: 'POST_DATA_TRY',
  POST_DATA_SUCCESS: 'POST_DATA_SUCCESS',
  POST_DATA_FAILED: 'POST_DATA_FAILED',
};

export const usersDataTypes = {
  USERS_DATA_UPDATE: 'USERS_DATA_UPDATE',
  USERS_DATA_TRY: 'USERS_DATA_TRY',
  USERS_DATA_SUCCESS: 'USERS_DATA_SUCCESS',
  USERS_DATA_FAILED: 'USERS_DATA_FAILED',
};

export const commentsDataTypes = {
  COMMENTS_DATA_UPDATE: 'COMMENTS_DATA_UPDATE',
  COMMENTS_DATA_STOP: 'COMMENTS_DATA_STOP',
  COMMENTS_DATA_TRY: 'COMMENTS_DATA_TRY',
  COMMENTS_DATA_SUCCESS: 'COMMENTS_DATA_SUCCESS',
  COMMENTS_DATA_FAILED: 'COMMENTS_DATA_FAILED',
};
