export const appDataConfigTypes = {
  APP_DATA_CONFIG_UPDATE: 'APP_DATA_CONFIG_UPDATE',
  // APP_DATA_CONFIG_TRY: 'APP_DATA_CONFIG_TRY',
  // APP_DATA_CONFIG_SUCCESS: 'APP_DATA_CONFIG_SUCCESS',
  // APP_DATA_CONFIG_FAILED: 'APP_DATA_CONFIG_FAILED',
};

export const postDataTypes = {
  POST_DATA_UPDATE: 'POST_DATA_UPDATE',
  POST_DATA_DISABLE_UNREAD: 'POST_DATA_DISABLE_UNREAD',
  POST_DATA_ADD_FAVORITE: 'POST_DATA_ADD_FAVORITE',
  POST_DATA_HIDE_FAVORITE: 'POST_DATA_HIDE_FAVORITE',
  POST_DATA_DELETE_ITEM: 'POST_DATA_DELETE_ITEM',
  POST_DATA_TRY: 'POST_DATA_TRY',
  POST_DATA_SUCCESS: 'POST_DATA_SUCCESS',
  POST_DATA_FAILED: 'POST_DATA_FAILED',
};

export const usersDataTypes = {
  USERS_DATA_UPDATE: 'USERS_DATA_UPDATE',
  USERS_DATA_TRY: 'USERS_DATA_TRY',
  USERS_DATA_SUCCESS: 'USERS_DATA_SUCCESS',
  USERS_DATA_FAILED: 'USERS_DATA_FAILED',
};
